services:
  - type: web
    name: one-piece-classifier
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: 5001
